//tealium universal tag - utag.1410 ut4.0.202101150920, Copyright 2021 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.defer=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){s.pt=function(x,d,f,a){var s=this,t=x,z=0,y,r;while(t){y=t.indexOf(d);y=y<0?t.length:y;t=t.substring(0,y);r=s[f](t,a);if(r)return r;z+=y+d.length;t=x.substring(z,x.length);t=z<x.length?t:''}
return''}
s.setuserprofile=function(){var s=this;var cookiecc;cookiecc=getCookieSC("sc_escliente_par");var cliente=0;var compra=0;if(s.event13||s.purchaseID||((typeof(s.pageName)=="string")&&(s.pageName.search("confirmacion")>-1))){compra=1;}
if(s.eVar60){cliente=1;}
if(cliente==1&&!cookiecc){setCookieSC("sc_escliente_par","cliente",1095);}else if(cookiecc=="Cliente"&&compra==1){setCookieSC("sc_escliente_par","cliente->compra",1095);}else if(compra==1&&!cookiecc){setCookieSC("sc_escliente_par","compra",1095);}else if(cookiecc=="Compra"&&cliente==1){setCookieSC("sc_escliente_par","compra->cliente",1095);}
cookiecc=getCookieSC("sc_escliente_par");if(cookiecc){s.eVar36="prospecto"+"->"+cookiecc;}else{s.eVar36="prospecto";}}
s.settrackpar=function(){var s=this;var ref=document.referrer;var isfirstaccessdt=s.getValOnce('isfirstaccessdt','s_firstaccessdt',0);if(ref==''&&isfirstaccessdt){var aux="Trafico Directo";setCookieDomainSC("sc_trackpar",aux,0,".vodafone.es");}else if(s.isSearchEngine(ref)){var aux="seoTraffic";setCookieDomainSC("sc_trackpar",aux,0,".vodafone.es");}
if(s.Util.getQueryParam('cid')!=''){var aux2=s.Util.getQueryParam('cid');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","cid:"+aux2,0,".vodafone.es");}}else if(s.Util.getQueryParam('emd')!=''){var aux2=s.Util.getQueryParam('emd');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","emd:"+aux2,0,".vodafone.es");}}else if(s.Util.getQueryParam('did')!=''){var aux2=s.Util.getQueryParam('did');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","did:"+aux2,0,".vodafone.es");}}else if(s.Util.getQueryParam('afe')!=''){var aux2=s.Util.getQueryParam('afe');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","afe:"+aux2,0,".vodafone.es");}}else if(s.Util.getQueryParam('afd')!=''){var aux2=s.Util.getQueryParam('afd');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","afd:"+aux2,0,".vodafone.es");}}else if(s.Util.getQueryParam('afp')!=''){var aux2=s.Util.getQueryParam('afp');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","afp:"+aux2,0,".vodafone.es");}}else if(s.Util.getQueryParam('ned')!=''){var aux2=s.Util.getQueryParam('ned');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","ned:"+aux2,0,".vodafone.es");}}else if(s.Util.getQueryParam('sms')!=''){var aux2=s.Util.getQueryParam('sms');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","sms:"+aux2,0,".vodafone.es");}}else if(s.Util.getQueryParam('psm')!=''){var aux2=s.Util.getQueryParam('psm');aux2=s.getValOnce(aux2,'aux2',0);if(aux2){setCookieDomainSC("sc_trackpar","psm:"+aux2,0,".vodafone.es");}}else if(ref&&(ref.indexOf("vodafone.es")==-1)){var aux2="Referring Domain";var track=getCookieSC("s_trackpar");if(!track){ref2=ref.match(/:\/\/(.[^/]+)/)[1];}
setCookieDomainSC("sc_trackpar",aux2+":"+ref2,0,".vodafone.es");}}
s.isSearchEngine=new Function("ref",""
+"var se='.google.,search.yahoo.com,search.live.,.aol.,search.netscape"
+".,altavista.com,ask.com,buscador.terra,.lycos.,alltheweb.com,buscar."
+"hispavista.com,gigablast.com,busca.starmedia,buscar.ozu,.bing.com';s"
+"e=se.split(',');for(var i=0;i<se.length;i++){if(ref.match(se[i])!=nu"
+"ll)return true;}return false;");s.getNewRepeat=new Function(""
+"var s=this,e=new Date(),cval,ct=e.getTime(),y=e.getYear();e.setTime"
+"(ct+30*24*60*60*1000);cval=s.c_r('s_nr');if(cval.length==0){s.c_w("
+"'s_nr',ct,e);return 'New';}if(cval.length!=0&&ct-cval<30*60*1000){s"
+".c_w('s_nr',ct,e);return 'New';}if(cval<1123916400001){e.setTime(cv"
+"al+30*24*60*60*1000);s.c_w('s_nr',ct,e);return 'Repeat';}else retur"
+"n 'Repeat';");s.checklandingvodafone=function(){var refer=document.referrer;var url=window.location.href.indexOf("vodafone.es");if(url!=-1){if(refer.indexOf("cookingideas.")!=-1||refer.indexOf("smartblog.")!=-1||refer.indexOf("vodafoneesmusica.")!=-1||refer.indexOf("fundacion.vodafone.")!=-1||refer.indexOf("vodafoneteayuda.")!=-1){s.eVar67=window.location.href;}}
else{s.eVar67="";}}
s.getValOnce=new Function("v","c","e",""
+"var s=this,a=new Date,v=v?v:v='',c=c?c:c='s_gvo',e=e?e:0,k=s.c_r(c"
+");if(v){a.setTime(a.getTime()+e*86400000);s.c_w(c,v,e?a:0);}return"
+" v==k?'':v");s.crossVisitParticipation=new Function("v","cn","ex","ct","dl","ev","dv",""
+"var s=this,ce;if(typeof(dv)==='undefined')dv=0;if(s.events&&ev){var"
+" ay=s.split(ev,',');var ea=s.split(s.events,',');for(var u=0;u<ay.l"
+"ength;u++){for(var x=0;x<ea.length;x++){if(ay[u]==ea[x]){ce=1;}}}}i"
+"f(!v||v==''){if(ce){s.c_w(cn,'');return'';}else return'';}v=escape("
+"v);var arry=new Array(),a=new Array(),c=s.c_r(cn),g=0,h=new Array()"
+";if(c&&c!=''){arry=s.split(c,'],[');for(q=0;q<arry.length;q++){z=ar"
+"ry[q];z=s.repl(z,'[','');z=s.repl(z,']','');z=s.repl(z,\"'\",'');arry"
+"[q]=s.split(z,',')}}var e=new Date();e.setFullYear(e.getFullYear()+"
+"5);if(dv==0&&arry.length>0&&arry[arry.length-1][0]==v)arry[arry.len"
+"gth-1]=[v,new Date().getTime()];else arry[arry.length]=[v,new Date("
+").getTime()];var start=arry.length-ct<0?0:arry.length-ct;var td=new"
+" Date();for(var x=start;x<arry.length;x++){var diff=Math.round((td."
+"getTime()-arry[x][1])/86400000);if(diff<ex){h[g]=unescape(arry[x][0"
+"]);a[g]=[arry[x][0],arry[x][1]];g++;}}var data=s.join(a,{delim:',',"
+"front:'[',back:']',wrap:\"'\"});s.c_w(cn,data,e);var r=s.join(h,{deli"
+"m:dl});if(ce)s.c_w(cn,'');return r;");s.apl=new Function("l","v","d","u",""
+"var s=this,m=0;if(!l)l='';if(u){var i,n,a=s.split(l,d);for(i=0;i<a."
+"length;i++){n=a[i];m=m||(u==1?(n==v):(n.toLowerCase()==v.toLowerCas"
+"e()));}}if(!m)l=l?l+d+v:v;return l");s.join=new Function("v","p",""
+"var s = this;var f,b,d,w;if(p){f=p.front?p.front:'';b=p.back?p.back"
+":'';d=p.delim?p.delim:'';w=p.wrap?p.wrap:'';}var str='';for(var x=0"
+";x<v.length;x++){if(typeof(v[x])=='object' )str+=s.join( v[x],p);el"
+"se str+=w+v[x]+w;if(x<v.length-1)str+=d;}return f+str+b;");s.repl=new Function("x","o","n",""
+"var i=x.indexOf(o),l=n.length;while(x&&i>=0){x=x.substring(0,i)+n+x."
+"substring(i+o.length);i=x.indexOf(o,i+l)}return x");s.split=new Function("l","d",""
+"var i,x=0,a= new Array;while(l){i=l.indexOf(d);i=i>-1?i:l.length;a[x"
+"++]=l.substring(0,i);l=l.substring(i+d.length);}return a");s.manageVars=new Function("c","l","f",""
+"var s=this,vl,la,vla;l=l?l:'';f=f?f:1 ;if(!s[c])return false;vl='pa"
+"geName,purchaseID,channel,server,pageType,campaign,state,zip,events"
+",products,transactionID';for(var n=1;n<76;n++){vl+=',prop'+n+',eVar"
+"'+n+',hier'+n;}if(l&&(f==1||f==2)){if(f==1){vl=l;}if(f==2){la=s.spl"
+"it(l,',');vla=s.split(vl,',');vl='';for(x in la){for(y in vla){if(l"
+"a[x]==vla[y]){vla[y]='';}}}for(y in vla){vl+=vla[y]?','+vla[y]:'';}"
+"}s.pt(vl,',',c,0);return true;}else if(l==''&&f==1){s.pt(vl,',',c,0"
+");return true;}else{return false;}");s.clearVars=new Function("t","var s=this;s[t]='';");s.lowercaseVars=new Function("t",""
+"var s=this;if(s[t]&&t!='events'){s[t]=s[t].toString();if(s[t].index"
+"Of('D=')!=0){s[t]=s[t].toLowerCase();}}");s.getVisitStart=new Function("c",""
+"var s=this,v=1,t=new Date;t.setTime(t.getTime()+1800000);if(s.c_r(c"
+")){v=0}if(!s.c_w(c,1,t)){s.c_w(c,1,0)}if(!s.c_r(c)){v=0}return v;");s.performanceTiming=new Function("v",""
+"var s=this;if(v)s.ptv=v;if(typeof performance!='undefined'){if(perf"
+"ormance.timing.loadEventEnd==0){s.pi=setInterval(function(){s.perfo"
+"rmanceWrite()},250);}if(!s.ptc||s.linkType=='e'){s.performanceRead("
+");}else{s.rfe();s[s.ptv]='';}}");s.performanceWrite=new Function("",""
+"var s=this;if(performance.timing.loadEventEnd>0)clearInterval(s.pi)"
+";try{if(s.c_r('s_ptc')==''&&performance.timing.loadEventEnd>0){try{"
+"var pt=performance.timing;var pta='';pta=s.performanceCheck(pt.fetc"
+"hStart,pt.navigationStart);pta+='^^'+s.performanceCheck(pt.domainLo"
+"okupStart,pt.fetchStart);pta+='^^'+s.performanceCheck(pt.domainLook"
+"upEnd,pt.domainLookupStart);pta+='^^'+s.performanceCheck(pt.connect"
+"End,pt.connectStart);pta+='^^'+s.performanceCheck(pt.responseStart,"
+"pt.connectEnd);pta+='^^'+s.performanceCheck(pt.responseEnd,pt.respo"
+"nseStart);pta+='^^'+s.performanceCheck(pt.loadEventStart,pt.domLoad"
+"ing);pta+='^^'+s.performanceCheck(pt.loadEventEnd,pt.loadEventStart"
+");pta+='^^'+s.performanceCheck(pt.loadEventEnd,pt.navigationStart);"
+"s.c_w('s_ptc',pta);if(sessionStorage&&navigator.cookieEnabled&&s.pt"
+"v!='undefined'){var pe=performance.getEntries();var tempPe='';for(v"
+"ar i=0;i<pe.length;i++){tempPe+='!';tempPe+=pe[i].name.indexOf('?')"
+">-1?pe[i].name.split('?')[0]:pe[i].name;tempPe+='|'+(Math.round(pe["
+"i].startTime)/1000).toFixed(1)+'|'+(Math.round(pe[i].duration)/1000"
+").toFixed(1)+'|'+pe[i].initiatorType;}sessionStorage.setItem('s_pec"
+"',tempPe);}}catch(err){return;}}}catch(err){return;}");s.performanceCheck=new Function("a","b",""
+"if(a>=0&&b>=0){if((a-b)<60000&&((a-b)>=0)){return((a-b)/1000).toFix"
+"ed(2);}else{return 600;}}");s.performanceRead=new Function("",""
+"var s=this;if(performance.timing.loadEventEnd>0)clearInterval(s.pi)"
+";var cv=s.c_r('s_ptc');if(s.pte){var ela=s.pte.split(',');}if(cv!='"
+"'){var cva=s.split(cv,'^^');if(cva[1]!=''){for(var x=0;x<(ela.lengt"
+"h-1);x++){s.events=s.apl(s.events,ela[x]+'='+cva[x],',',2);}}s.even"
+"ts=s.apl(s.events,ela[ela.length-1],',',2);}s.linkTrackEvents=s.apl"
+"(s.linkTrackEvents,s.pte,',',2);s.c_w('s_ptc','',0);if(sessionStora"
+"ge&&navigator.cookieEnabled&&s.ptv!='undefined'){s[s.ptv]=sessionSt"
+"orage.getItem('s_pec');sessionStorage.setItem('s_pec','',0);}else{s"
+"[s.ptv]='sessionStorage Unavailable';}s.ptc=true;");s.rfe=new Function("",""
+"var s=this;var ea=s.split(s.events,',');var pta=s.split(s.pte,',');"
+"try{for(x in pta){s.events=s.rfl(s.events,pta[x]);s.contextData['ev"
+"ents']=s.events;}}catch(e){return;}");s.rfl=new Function("l","v","d1","d2","ku",""
+"var s=this,R=new Array(),C='',d1=!d1?',':d1,d2=!d2?',':d2,ku=!ku?0:"
+"1;if(!l)return'';L=l.split(d1);for(i=0;i<L.length;i++){if(L[i].inde"
+"xOf(':')>-1){C=L[i].split(':');C[1]=C[0]+':'+C[1];L[i]=C[0];}if(L[i"
+"].indexOf('=')>-1){C=L[i].split('=');C[1]=C[0]+'='+C[1];L[i]=C[0];}"
+"if(L[i]!=v&&C)R.push(C[1]);else if(L[i]!=v)R.push(L[i]);else if(L[i"
+"]==v&&ku){ku=0;if(C)R.push(C[1]);else R.push(L[i]);}C='';}return s."
+"join(R,{delim:d2})");s.getPreviousValue=new Function("v","c","el",""
+"var s=this,t=new Date,i,j,r='';t.setTime(t.getTime()+1800000);if(el"
+"){if(s.events){i=s.split(el,',');j=s.split(s.events,',');for(x in i"
+"){for(y in j){if(i[x]==j[y]){if(s.c_r(c)) r=s.c_r(c);v?s.c_w(c,v,t)"
+":s.c_w(c,'no value',t);return r}}}}}else{if(s.c_r(c)) r=s.c_r(c);v?"
+"s.c_w(c,v,t):s.c_w(c,'no value',t);return r}");s.getVisitDuration=function(){var d=new Date,c=d.getTime(),b=this.c_r("s_dur");if(isNaN(b)||18E5<c-b)b=c;var a=c-b;d.setTime(c+18E5);this.c_w("s_dur",b+"",d);if(0===a)return"first hit of visit";a=Math.floor(a/6E4);return 0===a?"less than a minute":1===a?"1 minute":a+" minutes"};},function(a,b){try{if(1){var q_aa_params=JSON.stringify({marketingCloudVisitorID:visitor.getMarketingCloudVisitorID()});var urlMedallia=window.location.href;var referrerMedallia=document.referrer;var segmentoM;var triggerMedallia="";var trigger72h="";var trigger48h="";var regexTest=function(regex,url){var result=regex.test(url);return result;}
if(document.querySelector('li.active')){segmentoM=document.querySelector('li.active').textContent;}
var regexGTopUp=/www.vodafone.es\/particulares\/es\/tienda\/tarifas-para-movil\/recarga-de-tarjeta(.*)action=validar(.*)/;var regexGTopUp2=/www.vodafone.es\/particulares\/es\/tienda\/movil\/tarifas-prepago-y-recargas\/recarga-de-tarjeta(.*)action=validar(.*)/;var regexGTopUp3=/www.vodafone.es\/particulares\/es\/tienda\/movil\/tarifas-prepago-y-recargas\/recarga-tarjeta(.*)action=validar(.*)/;try{if(regexTest(regexGTopUp,urlMedallia)||regexTest(regexGTopUp2,urlMedallia)||regexTest(regexGTopUp3,urlMedallia)){triggerMedallia="top_up";}}catch(e){};var regexGHS=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/(.*)\/(.*)\/$/;try{if(regexTest(regexGHS,urlMedallia)){triggerMedallia="g_hs";}}catch(e){};var regexWP_PAR=/(http|https):\/\/www\.vodafone\.es\/(c\/)?particulares\/es\/(.*)/;var regexWP_PAR2=/(http|https):\/\/www\.vodafone\.es\/c\/conocenos\/es\/vodafone-espana\/(.*)/;try{if(regexTest(regexWP_PAR,referrerMedallia)||regexTest(regexWP_PAR2,referrerMedallia)){triggerMedallia="wp_par";}}catch(e){};var regexWP_AUT=/(http|https):\/\/www\.vodafone\.es\/c\/autonomos\/es\/(.*)/;try{if(regexTest(regexWP_AUT,urlMedallia)){triggerMedallia="wp_aut";}}catch(e){};var regexWP_COR=/(http|https):\/\/www\.vodafone\.es\/c\/grandes-clientes\/es\/(.*)/;try{if(regexTest(regexWP_COR,urlMedallia)){triggerMedallia="wp_cor";}}catch(e){};var regexSEARCH=/(http|https):\/\/www\.vodafone\.es\/tools\/(es|es\/|es\?tb16(.*))$/;try{if(regexTest(regexSEARCH,referrerMedallia)){triggerMedallia="sear";}}catch(e){};var regexLHS=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/(.*)\/(.*)\/$/;try{if(regexTest(regexLHS,urlMedallia)){triggerMedallia="lhs";}}catch(e){};var regexADC_AUT=/https:\/\/www\.vodafone\.es\/areaclientes_me\/(.*)/;try{if(regexTest(regexADC_AUT,urlMedallia)){triggerMedallia="adcaut";}}catch(e){};var regexADC_EMP=/https:\/\/www\.vodafone\.es\/areaclientes\/empresas\/es\/(.*)/;try{if(regexTest(regexADC_EMP,urlMedallia)){triggerMedallia="adcemp";}}catch(e){};var regexAP_MVF=/https:\/\/www\.vodafone\.es\/mivodafone\/es\/(.*)/;try{if(regexTest(regexAP_MVF,urlMedallia)){triggerMedallia="ap_mvf";}}catch(e){};var regexLHSM=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/(.*)\/(.*)\/$/;var regexLHSM2=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/internet-fijo-y-vodafone-one\/(.*)\/(.*)\//;var regexLHSM3=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/television\/(.*)\/(.*)\//;var regexLHSM4=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/moviles-tablets-y-apps\/(.*)\/(.*)\//;var regexLHSM5=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/tarifas\/(.*)\/(.*)\//;var regexLHSM6=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/facturacion\/entiende-tu-factura\/(.*)\//;var regexLHSM7=/(http|https):\/\/ayudacliente\.vodafone\.es\/particulares\/area-privada-mi-vodafone\/gestiones-y-servicios\/(.*)\//;var regexLHSM8=/(http|https):\/\/ayudacliente\.vodafone\.es\/(autonomos|empresas)\/area-de-clientes\/area-de-clientes-desde-el-movil\/(.*)\//;var regexLHSM9=/(http|https):\/\/ayudacliente\.vodafone\.es\/particulares\/soy-nuevo-en-vodafone\/primeros-pasos-area-privada-mi-vodafone\/(.*)\//;var regexLHSM10=/(http|https):\/\/ayudacliente\.vodafone\.es\/(autonomos|empresas)\/soy-nuevo-en-vodafone\/primeros-pasos-en-tu-area-de-clientes\/(.*)\//;var regexLHSM11=/(http|https):\/\/manuales\.vodafone\.es\//;var regexLHSM12=/(http|https):\/\/ayudacliente\.vodafone\.es\/(particulares|autonomos|empresas)\/guias-paso-a-paso\/(.*)\/(.*)\//;var regexLHSM12=/(http|https):\/\/ayudacliente.vodafone.es\/particulares\/videos\//;try{if(regexTest(regexLHSM,urlMedallia)){triggerMedallia="lhsm";}else if(regexTest(regexLHSM2,urlMedallia)||regexTest(regexLHSM3,urlMedallia)||regexTest(regexLHSM4,urlMedallia)||regexTest(regexLHSM5,urlMedallia)||regexTest(regexLHSM6,urlMedallia)||regexTest(regexLHSM7,urlMedallia)||regexTest(regexLHSM8,urlMedallia)||regexTest(regexLHSM9,urlMedallia)||regexTest(regexLHSM10,urlMedallia)||regexTest(regexLHSM11,urlMedallia)||regexTest(regexLHSM12,urlMedallia)){triggerMedallia="lhsm2";}}catch(e){};try{var urlChat=window.location.href;urlChat.replace(/[\[\]]/g,"\\$&");if(urlChat.indexOf("tipoEncuesta=encPostchat")!==-1){var regex=new RegExp("[?&]"+"timeMed"+"(=([^&#]*)|&|#|$)"),results=regex.exec(urlChat);if(results&&results[2]){var fecha=results[2].split("__")[0];var year=fecha.split("-")[2];var month=fecha.split("-")[1];var day=fecha.split("-")[0];var hora=results[2].split("__")[1];var seconds=hora.split(":")[2];var minutes=hora.split(":")[1];var hours=hora.split(":")[0];var fechaUrl=new Date(year,month-1,day,hours,minutes,seconds);var datetimeCompare=new Date(Date.now());datetimeCompare.setHours(datetimeCompare.getHours()-24);if(datetimeCompare<fechaUrl){triggerMedallia="postChat";}}}}catch(e){};try{var urlChat=window.location.href.toLowerCase();urlChat.replace(/[\[\]]/g,"\\$&");if(urlChat.indexOf("chat")!==-1&&urlChat.indexOf("source=")!==-1){var regex=new RegExp("[?&]"+"timemed"+"(=([^&#]*)|&|#|$)"),results=regex.exec(urlChat);if(results&&results[2]){var fecha=results[2].split("t")[0];var year=fecha.split("-")[0];var month=fecha.split("-")[1];var day=fecha.split("-")[2];var hora=results[2].split("t")[1];if(hora.indexOf(":")>-1){var seconds=hora.split(":")[2].substr(0,2);var minutes=hora.split(":")[1];var hours=hora.split(":")[0];}
else{var seconds=hora.split("%3a")[2].substr(0,2);var minutes=hora.split("%3a")[1];var hours=hora.split("%3a")[0];}
var fechaUrl=new Date(year,month-1,day,hours,minutes,seconds);var datetimeCompare=new Date(Date.now());datetimeCompare.setHours(datetimeCompare.getHours()-24);if(datetimeCompare<fechaUrl){triggerMedallia="postChatNuevo";}}}}catch(e){};try{var urlChat=window.location.href.toLowerCase();urlChat.replace(/[\[\]]/g,"\\$&");if(urlChat.indexOf("chat")!==-1&&urlChat.indexOf("timemed=")!==-1){var regex=new RegExp("[?&]"+"timemed"+"(=([^&#]*)|&|#|$)"),results=regex.exec(urlChat);if(results&&results[2]){var fecha=results[2].split("t")[0];var year=fecha.split("-")[0];var month=fecha.split("-")[1];var day=fecha.split("-")[2];var hora=results[2].split("t")[1];if(hora.indexOf(":")>-1){var seconds=hora.split(":")[2].substr(0,2);var minutes=hora.split(":")[1];var hours=hora.split(":")[0];}
else{var seconds=hora.split("%3a")[2].substr(0,2);var minutes=hora.split("%3a")[1];var hours=hora.split("%3a")[0];}
var fechaUrl=new Date(year,month-1,day,hours,minutes,seconds);var datetimeCompare=new Date(Date.now());datetimeCompare.setHours(datetimeCompare.getHours()-72);if(datetimeCompare<fechaUrl){trigger72h="true";}}}}catch(e){};try{var urlChat=window.location.href.toLowerCase();urlChat.replace(/[\[\]]/g,"\\$&");if(urlChat.indexOf("chat")!==-1&&urlChat.indexOf("timemed=")!==-1){var regex=new RegExp("[?&]"+"timemed"+"(=([^&#]*)|&|#|$)"),results=regex.exec(urlChat);if(results&&results[2]){var fecha=results[2].split("t")[0];var year=fecha.split("-")[0];var month=fecha.split("-")[1];var day=fecha.split("-")[2];var hora=results[2].split("t")[1];if(hora.indexOf(":")>-1){var seconds=hora.split(":")[2].substr(0,2);var minutes=hora.split(":")[1];var hours=hora.split(":")[0];}
else{var seconds=hora.split("%3a")[2].substr(0,2);var minutes=hora.split("%3a")[1];var hours=hora.split("%3a")[0];}
var fechaUrl=new Date(year,month-1,day,hours,minutes,seconds);var datetimeCompare=new Date(Date.now());datetimeCompare.setHours(datetimeCompare.getHours()-48);if(datetimeCompare<fechaUrl){trigger48h="true";}}}}catch(e){};utag_data['triggerMedallia']=triggerMedallia;utag_data['segmentoM']=segmentoM;utag_data['q_aa_params']=q_aa_params;utag_data['trigger72h']=trigger72h;utag_data['trigger48h']=trigger48h;}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
var s=document.createElement("script");s.type="text/javascript";s.defer="true";s.src="https://nebula-cdn.kampyle.com/we/62238/onsite/embed.js";document.querySelector("head").append(s);}};utag.o[loader].loader.LOAD(id);})("1410","vodafone.es-main");}catch(error){utag.DB(error);}
