//tealium universal tag - utag.2083 ut4.0.202101150920, Copyright 2021 Tealium.com Inc. All Rights Reserved.
!function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var
n=window.pintrk;n.queue=[],n.version="3.0";var
t=document.createElement("script");t.async=!0,t.src=e;var
r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){if((document.location.pathname.indexOf("/particulares")>-1||(typeof b=="object"&&typeof b["page_channel"]=="string"&&b["page_channel"].indexOf("particulares")>-1)||(typeof s=="object"&&typeof s.channel=="string"&&s.channel.indexOf("particulares")>-1))&&(document.location.hostname.indexOf("bit.vodafone")==-1||document.location.hostname.indexOf("yu.vodafone.es")==-1||document.location.hostname.indexOf("vodafoneyu.es")==-1)){try{pintrk('load','2612789585804');pintrk('page');var elements=[];var elemento;if(typeof utag.data.product_broadband_plan!='undefined'&&utag.data.product_broadband_plan!=''){elemento=sc_quita_tildes(utag.data.product_broadband_plan);elements.push(elemento);}
else if(typeof utag.data.product_mobile_plan!='undefined'&&utag.data.product_mobile_plan!=''){elemento=sc_quita_tildes(utag.data.product_mobile_plan);elements.push(elemento);}
else if(typeof utag.data.product_name!='undefined'&&utag.data.product_name!=''){elemento=sc_quita_tildes(utag.data.product_name);elements.push(elemento);}
else if(typeof utag.data.plans_list!='undefined'&&utag.data.plans_list){for(var i=0;i<utag.data.plans_list.length;i++){var elem=utag.data.plans_list[i];if(typeof elem.product_broadband_plan!='undefined'&&elem.product_broadband_plan!=''){elemento=sc_quita_tildes(elem.product_broadband_plan);elements.push(elemento);}
else if(typeof elem.product_mobile_plan!='undefined'&&elem.product_mobile_plan!=''){elemento=sc_quita_tildes(elem.product_mobile_plan);elements.push(elemento);}
else if(typeof elem.product_name!='undefined'&&elem.product_name!=''){elemento=sc_quita_tildes(elem.product_name);elements.push(elemento);}}}
var pageSubsection2="";if(typeof utag.data.page_subsection_2!='undefined'){pageSubsection2=b['page_subsection_2'];}
if(document.location.pathname.indexOf("/confirmacion-pedido")==-1||utag.data.page_funnel_step.indexOf(":confirmacion de pedido")==-1){if((typeof elemento=="object"&&elements.length>0)||(typeof utag.data.plans_list=="object"&&elements.length>1)){if(document.location.pathname.indexOf("/productos-y-servicios/vodafone-one")>-1||(document.location.pathname.indexOf("/es/productos-y-servicios/_t_/movil/contrato/tarifas-contrato/")>-1&&document.location.pathname.indexOf("tarifa-")==-1)||(document.location.pathname.indexOf("/es/productos-y-servicios/_t_/fibra-optica-adsl/")>-1&&document.location.pathname.indexOf("tarifa-")==-1)||(document.location.pathname.indexOf("/es/productos-y-servicios/_t_/fibra-adsl/")>-1&&document.location.pathname.indexOf("tarifa-")==-1)){pintrk('track','pagevisit',{funnel_step:pageSubsection2,content_ids:[elements.toString()]});}else{pintrk('track','pagevisit',{funnel_step:pageSubsection2,content_ids:[elements.toString()]});}}else if(typeof elemento=="string"&&elements.length>0){pintrk('track','pagevisit',{funnel_step:pageSubsection2,content_ids:elements.toString()});}else{pintrk('track','pagevisit',{funnel_step:pageSubsection2,content_ids:""});}}else if(document.location.pathname.indexOf("/confirmacion-pedido")>-1||utag.data.page_funnel_step.indexOf(":confirmacion de pedido")>-1){if(elements.length>0){pintrk('track','checkout',{funnel_step:pageSubsection2,content_ids:elements.toString(),order_quantity:1});}else{pintrk('track','checkout',{funnel_step:pageSubsection2,content_ids:"",order_quantity:1});}}
if(document.location.pathname.indexOf("/contratacion/completa-tu-pedido")>-1){if(elements.length>0){pintrk('track','addtocart',{funnel_step:pageSubsection2,content_ids:elements.toString(),order_quantity:1});}else{pintrk('track','addtocart',{funnel_step:pageSubsection2,content_ids:"",order_quantity:1});}}}
catch(e){}}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("2083","vodafone.es-main");}catch(error){utag.DB(error);}
