//tealium universal tag - utag.1521 ut4.0.202101221415, Copyright 2021 Tealium.com Inc. All Rights Reserved.
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){if((document.location.pathname.indexOf("/particulares")>-1||document.location.pathname.indexOf("/oferta/hogar-ilimitable")>-1||(typeof b=="object"&&typeof b["page_channel"]=="string"&&b["page_channel"].indexOf("particulares")>-1)||(typeof s=="object"&&typeof s.channel=="string"&&s.channel.indexOf("particulares")>-1))&&(document.location.hostname.indexOf("bit.vodafone")==-1||document.location.hostname.indexOf("yu.vodafone.es")==-1||document.location.hostname.indexOf("vodafoneyu.es")==-1)){try{fbq('init','246109326227022');fbq('track',"PageView");var elements=[];var elemento;if(typeof utag.data.product_broadband_plan!='undefined'&&utag.data.product_broadband_plan!=''){elemento=sc_quita_tildes(utag.data.product_broadband_plan);elements.push(elemento);}
else if(typeof utag.data.product_mobile_plan!='undefined'&&utag.data.product_mobile_plan!=''){elemento=sc_quita_tildes(utag.data.product_mobile_plan);elements.push(elemento);}
else if(typeof utag.data.product_name!='undefined'&&utag.data.product_name!=''){elemento=sc_quita_tildes(utag.data.product_name);elements.push(elemento);}
else if(typeof utag.data.plans_list!='undefined'&&utag.data.plans_list){for(var i=0;i<utag.data.plans_list.length;i++){var elem=utag.data.plans_list[i];if(typeof elem.product_broadband_plan!='undefined'&&elem.product_broadband_plan!=''){elemento=sc_quita_tildes(elem.product_broadband_plan);elements.push(elemento);}
else if(typeof elem.product_mobile_plan!='undefined'&&elem.product_mobile_plan!=''){elemento=sc_quita_tildes(elem.product_mobile_plan);elements.push(elemento);}
else if(typeof elem.product_name!='undefined'&&elem.product_name!=''){elemento=sc_quita_tildes(elem.product_name);elements.push(elemento);}}}
var pageSubsection2="";if(typeof utag.data.page_subsection_2!='undefined'){pageSubsection2=b['page_subsection_2'];}
if(document.location.pathname.indexOf("/confirmacion-pedido")==-1||utag.data.page_funnel_step.indexOf(":confirmacion de pedido")==-1){if((typeof elemento=="object"&&elements.length>0)||(typeof utag.data.plans_list=="object"&&elements.length>1)){var contents=[];if(document.location.pathname.indexOf("/productos-y-servicios/vodafone-one")>-1||(document.location.pathname.indexOf("/es/productos-y-servicios/_t_/movil/contrato/tarifas-contrato/")>-1&&document.location.pathname.indexOf("tarifa-")==-1)||(document.location.pathname.indexOf("/es/productos-y-servicios/_t_/fibra-optica-adsl/")>-1&&document.location.pathname.indexOf("tarifa-")==-1)||(document.location.pathname.indexOf("/es/productos-y-servicios/_t_/fibra-adsl/")>-1&&document.location.pathname.indexOf("tarifa-")==-1)){for(var z=0;z<elements[0].length;z++){var fb_id={id:elements[0][z],quantity:1};contents.push(fb_id);}
fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:[elements.toString()],content_type:"product_group",contents});}else{for(var z=0;z<elements.length;z++){var fb_id={id:elements[z],quantity:1};contents.push(fb_id);}
fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:[elements.toString()],content_type:"product_group",contents});}}else if(typeof elemento=="string"&&elements.length>0){fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:elements,content_type:"product",contents:[{id:elements.toString(),quantity:1}]});}else{fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:"",content_type:"",contents:[{id:"",quantity:1}]});}}else if(document.location.pathname.indexOf("/confirmacion-pedido")>-1||utag.data.page_funnel_step.indexOf(":confirmacion de pedido")>-1){if(elements.length>0){fbq('track','Purchase',{funnel_step:pageSubsection2,content_ids:elements.toString(),content_type:"product",contents:[{id:elements.toString(),quantity:1}]});}else{fbq('track','Purchase',{funnel_step:pageSubsection2,content_ids:"",content_type:"product",contents:[{id:"",quantity:1}]});}}
if(document.location.pathname.indexOf("/contratacion/completa-tu-pedido")>-1){if(elements.length>0){fbq('track','AddToCart',{funnel_step:pageSubsection2,content_ids:elements.toString(),content_type:"product",contents:[{id:elements.toString(),quantity:1}]});}else{fbq('track','AddToCart',{funnel_step:pageSubsection2,content_ids:"",content_type:"product",contents:[{id:"",quantity:1}]});}}}
catch(e){}}
if((document.location.pathname.indexOf("/empresas")>-1||(typeof b=="object"&&typeof b["page_channel"]=="string"&&b["page_channel"].indexOf("autonomos")>-1))&&(document.location.hostname.indexOf("bit.vodafone")==-1||document.location.hostname.indexOf("yu.vodafone.es")==-1||document.location.hostname.indexOf("vodafoneyu.es")==-1)){try{fbq('init','550722692335085');fbq('track',"PageView");var elements=[];var elemento;if(typeof utag.data.product_broadband_plan!='undefined'&&utag.data.product_broadband_plan!=''){elemento=utag.data.product_broadband_plan;elements.push(elemento);}
else if(typeof utag.data.product_mobile_plan!='undefined'&&utag.data.product_mobile_plan!=''){elemento=utag.data.product_mobile_plan;elements.push(elemento);}
else if(typeof utag.data.product_name!='undefined'&&utag.data.product_name!=''){elemento=utag.data.product_name;elements.push(elemento);}
else if(typeof utag.data.plans_list!='undefined'&&utag.data.plans_list){for(var i=0;i<utag.data.plans_list.length;i++){var elem=utag.data.plans_list[i];if(typeof elem.product_broadband_plan!='undefined'&&elem.product_broadband_plan!=''){elemento=elem.product_broadband_plan;elements.push(elemento);}
else if(typeof elem.product_mobile_plan!='undefined'&&elem.product_mobile_plan!=''){elemento=elem.product_mobile_plan;elements.push(elemento);}
else if(typeof elem.product_name!='undefined'&&elem.product_name!=''){elemento=elem.product_name;elements.push(elemento);}}}
var pageSubsection2="";if(typeof utag.data.page_subsection_2!='undefined'){pageSubsection2=b['page_subsection_2'];}
if(document.location.pathname.indexOf("/confirmacion-pedido")==-1||utag.data.page_funnel_step.indexOf(":confirmacion de pedido")==-1){if((typeof elemento=="object"&&elements.length>0)||(typeof utag.data.plans_list=="object"&&elements.length>1)){fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:[elements.toString()],content_type:"product_group",contents:[{id:elements.toString(),quantity:1}]});}else if(typeof elemento=="string"&&elements.length>0){fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:elements,content_type:"product",contents:[{id:elements.toString(),quantity:1}]});}else{fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:"",content_type:"",contents:[{id:"",quantity:1}]});}}else if(document.location.pathname.indexOf("/confirmacion-pedido")>-1||utag.data.page_funnel_step.indexOf(":confirmacion de pedido")>-1){if(elements.length>0){fbq('track','Purchase',{funnel_step:pageSubsection2,content_ids:elements.toString(),content_type:"product",contents:[{id:elements.toString(),quantity:1}]});}else{fbq('track','Purchase',{funnel_step:pageSubsection2,content_ids:"",content_type:"product",contents:[{id:"",quantity:1}]});}}
if(document.location.pathname.indexOf("/contratacion/completa-tu-pedido")>-1){if(elements.length>0){fbq('track','AddToCart',{funnel_step:pageSubsection2,content_ids:elements,content_type:"product",contents:[{id:elements.toString(),quantity:1}]});}else{fbq('track','AddToCart',{funnel_step:pageSubsection2,content_ids:"",content_type:"product",contents:[{id:"",quantity:1}]});}}}catch(e){}}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){try{if(document.location.hostname.indexOf("yu.vodafone")>-1||document.location.hostname.indexOf("vodafoneyu.es")>-1||utag.data.page_channel=="yu"){fbq('init','1491226711026273');fbq('track',"PageView");var elements=[];var elemento;if(typeof utag.data.product_broadband_plan!='undefined'&&utag.data.product_broadband_plan!=''){elemento=utag.data.product_broadband_plan;elements.push(elemento);}
else if(typeof utag.data.product_mobile_plan!='undefined'&&utag.data.product_mobile_plan!=''){elemento=utag.data.product_mobile_plan;elements.push(elemento);}
else if(typeof utag.data.product_name!='undefined'&&utag.data.product_name!=''){elemento=utag.data.product_name;elements.push(elemento);}else if(typeof b["plans_list"]!='undefined'&&b["plans_list"]){for(var i=0;i<b["plans_list"].length;i++){var elem=b["plans_list"][i];if(typeof elem.product_broadband_plan!='undefined'&&elem.product_broadband_plan!=''){elemento=elem.product_broadband_plan;elements.push(elemento);}
else if(typeof elem.product_mobile_plan!='undefined'&&elem.product_mobile_plan!=''){elemento=elem.product_mobile_plan;elements.push(elemento);}
else if(typeof elem.product_name!='undefined'&&elem.product_name!=''){elemento=elem.product_name;elements.push(elemento);}}}
var pageSubsection3="";if(typeof utag.data.page_subsection_3!='undefined'){pageSubsection3=b['page_subsection_3'];}
var pageSubsection2="";if(typeof utag.data.page_subsection_2!='undefined'){pageSubsection2=b['page_subsection_2'];}
if(utag.data.page_name.indexOf(":gracias por tu compra")==-1&&document.location.pathname.indexOf("/tarifas-fibra-y-movil")==-1&&document.location.pathname.indexOf("/tarifa-fibra-optica")==-1&&document.location.pathname.indexOf("/tarifas-moviles")==-1&&utag.data.page_name.indexOf("ficha de tarifas")==-1){if(elements.length>1){fbq('track','ViewContent',{funnel_step:pageSubsection3,content_ids:elements,content_type:'product_group',contents:[{id:elements.toString(),quantity:1}]});}else if(elements.length==1){fbq('track','ViewContent',{funnel_step:pageSubsection3,content_ids:elements,content_type:'product',contents:[{id:elements.toString(),quantity:1}]});}else{fbq('track','ViewContent',{funnel_step:pageSubsection3,content_ids:"",content_type:"",contents:[{id:"",quantity:1}]});}}else if(utag.data.page_name.indexOf(":gracias por tu compra")==-1&&document.location.pathname.indexOf("/tarifa-fibra-optica")>-1||utag.data.page_name.indexOf("ficha de tarifas")>-1){if(elements.length>1){fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:elements,content_type:'product_group',contents:[{id:elements.toString(),quantity:1}]});}else if(elements.length==1){fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:elements,content_type:'product',contents:[{id:elements.toString(),quantity:1}]});}else{fbq('track','ViewContent',{funnel_step:pageSubsection2,content_ids:"",content_type:"",contents:[{id:"",quantity:1}]});}}else if(typeof b["transaction_id"]!='undefined'&&utag.data.page_funnel_step.indexOf(":gracias por tu compra")>-1&&utag.data.page_name.indexOf(":gracias por tu compra")>-1&&utag.data.page_funnel_plan_type.indexOf("postpago")>-1){fbq('track','Purchase',{funnel_step:pageSubsection3,content_ids:elements,content_type:'product',contents:[{id:elements.toString(),quantity:1}]});}else if(typeof b["transaction_id"]!='undefined'&&utag.data.page_funnel_step.indexOf(":gracias por tu compra")>-1&&utag.data.page_name.indexOf(":gracias por tu compra")>-1&&utag.data.page_funnel_plan_type.indexOf("prepago")>-1){fbq('track','Purchase_YU_Prepago',{funnel_step:pageSubsection3,content_ids:elements,content_type:'product',contents:[{id:elements.toString(),quantity:1}]});}}}catch(e){}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){try{if(document.location.hostname.indexOf("yu.vodafone")>-1||document.location.hostname.indexOf("vodafoneyu.es")>-1||utag.data.page_channel=="yu"){if(utag.data.page_subsection_4.indexOf("tipo operacion")>-1){var elements=[];var elemento;if(typeof utag.data.product_broadband_plan!='undefined'&&utag.data.product_broadband_plan!=''){elemento=utag.data.product_broadband_plan;elements.push(elemento);}
else if(typeof utag.data.product_mobile_plan!='undefined'&&utag.data.product_mobile_plan!=''){elemento=utag.data.product_mobile_plan;elements.push(elemento);}
else if(typeof utag.data.product_name!='undefined'&&utag.data.product_name!=''){elemento=utag.data.product_name;elements.push(elemento);}
var pageSubsection3="";if(typeof utag.data.page_subsection_3!='undefined'){pageSubsection3=b['page_subsection_3'];}
if(elements.length>0){fbq('track','AddToCart',{funnel_step:pageSubsection3,content_ids:elements,content_type:"product",contents:[{id:elements.toString(),quantity:1}]});}}}}catch(e){}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("1521","vodafone.es-main");}catch(error){utag.DB(error);}
